name: "JFrog Artifact Pull Example"
on: push

jobs:
  pull-artifact:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact from JFrog using curl
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        run: |
          # Use curl to download the artifact
          curl -H "Authorization: Bearer $JF_ACCESS_TOKEN" -O "$JF_URL/artifactory/knnpm-npm-local/path/to/artifacts/build_20241015102507.zip"

      - name: Unzip the downloaded artifact
        run: unzip build_20241015102507.zip
