name: "JFrog Artifact Pull Example"
on: push

jobs:
  pull-artifact:
     runs-on: ubuntu-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

       # Step to configure JFrog CLI with the Artifactory URL and token
       - name: Configure JFrog CLI
         run: |
           jf config add my-artifactory-server \
           --url=${{ secrets.JF_URL }} \
           --access-token=${{ secrets.JF_ACCESS_TOKEN }} \
           --interactive=false

       # Step to download the artifact from the specified JFrog URL
       - name: Download Artifact from JFrog
         run: jf rt dl "knnpm-npm-local/path/to/artifacts/build_20241015102507.zip" .

       - name: Unzip the downloaded artifact
         run: unzip build_20241015102507.zip
