name: "JFrog Integration Example"
on: push

jobs:
  pull-artifact:
     runs-on: ubuntu-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

       # Step to download the artifact from the specified JFrog URL
       - name: Download Artifact from JFrog
         run: |
           # Download artifact from JFrog Artifactory with explicit URL
           jf rt dl "knnpm-npm-local/path/to/artifacts/build_20241015102507.zip" . --url=${{ secrets.JF_URL }} --access-token=${{ secrets.JF_ACCESS_TOKEN }}
           
       - name: Unzip the downloaded artifact
         run: unzip build_20241015102507.zip
